version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_insecure_password
      MYSQL_DATABASE: journal
    ports:
      - "9906:3306"
    command: --init-file /init.sql
    volumes:
      - ./data:/var/lib/mysql
      - ./src/app/Database/init.sql:/init.sql
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx-config/conf.d:/etc/nginx/conf.d
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
  php:
    build: .
    image: my_php:1
    volumes:
      - ./src:/src
    depends_on:
      - db
